# Generated by Django 4.2.13 on 2024-05-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='deletedAtp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='updatedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
